name: Refresh Calendar

on:
  schedule:
    - cron: "0 * * * *" # aktuell jede Stunde
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install GEANT CA certificate
        run: |
          sudo mkdir -p /usr/local/share/ca-certificates/extra
          sudo cp certs/geant.pem /usr/local/share/ca-certificates/extra/geant.crt
          sudo chmod 644 /usr/local/share/ca-certificates/extra/geant.crt
          sudo update-ca-certificates

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.23.0"

      - name: Install dependencies
        run: go mod tidy

      - name: Run the program
        run: go run ./cmd/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin calendar-updates || git checkout -b calendar-updates
          git checkout calendar-updates
          mv ical/filtered_calendar.ics filtered_calendar.ics
          git add filtered_calendar.ics
          git commit -m "Update filtered_calendar.ics [skip ci]" || echo "No changes to commit"
          git push origin calendar-updates
